mysql_data:
  image: busybox
  container_name: mysql_data
  volumes:
    - "/var/lib/mysql"

mysql:
  image: mysql:5.6
  container_name: mysql
  hostname: mysql
  volumes_from:
    - mysql_data
  ports:
    - "3306:3306"
  environment:
    - "MYSQL_ROOT_PASSWORD=pass"

php70:
  image: yoshz/php-fpm-dev:7.0
  container_name: php70
  hostname: php70
  ports:
    - "2022:22"
  links:
    - "mysql:db"
  env_file: ".env_user"
  volumes:
    - "./www:/var/www"
  dns:
    - "8.8.8.8"
    - "8.8.4.4"
  
nginx:
  image: nginx
  container_name: nginx
  hostname: nginx
  links:
    - "php70:web"
  ports:
    - "80:80"
  volumes:
    - "./www:/var/www"
    - "./configs/nginx:/etc/nginx/conf.d"
