version: '2'

volumes:
  mysql_data:
    driver: local

services:
  mysql:
    image: mysql:5.6
    volumes:
      - "mysql_data:/var/lib/mysql"
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=pass"

  memcached:
    image: memcached
    mem_limit: 64M

  php:
    image: yoshz/php-fpm-dev:7.0
    hostname: php
    ports:
      - "2022:22"
      - "35729:35729"
    env_file: "./configs/env_user"
    volumes:
      - "./www:/var/www"
    dns:
      - "8.8.8.8"
      - "8.8.4.4"
    
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - "./www:/var/www"
      - "./configs/nginx:/etc/nginx/conf.d"
